apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocd
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd
    spec:
      - name: argocdcon
        image: nanajanashia/argocd-app:1.0