apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocdone
  replicas: 2
  template:
    metadata:
      labels:
        app: argocdone
    spec:
      containers:
        - name: pavan
          image: pavan923/k8s:8
          ports:
          - containerPort: 5000
