apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocd1
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd1
    spec:
      containers:
        - name: argocdcon
          image: nginx
          ports:
          - containerPort: 8080
