apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocdone
  replicas: 1
  template:
    metadata:
      labels:
        app: argocdone
    spec:
      imagePullSecrets: 
        - name: docker-sec
      containers:
        - name: pavan
          image: pavan923/k10s:12
          ports:
          - containerPort: 5000
