apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocd
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: argocdcon
          image: nginx